### ISSUE TITLE
UINavigationViewControllerを使ってsegueした場合の初期表示不具合

### ISSUE THREAD

**Issue by MasaruKitajima** [jtaka1012/SGLAccordionTableView#8]
素晴らしいアコーディオンテーブルビューを有難うございます。

非常に良いのですが、UINavigationControllerをInitialViewに持つプロジェクトの途中で、SGLAccordionTableViewを利用すると、初期表示の場合のみ、Section0の上に空白ができます。

その後スクロールで上いっぱいまで一度でも表示すると現象は再現しません。
![img_2064](https://cloud.githubusercontent.com/assets/3312530/15984957/9aa2f5de-3017-11e6-8ee8-2c0d6e085bc9.png)

これが解決されれば、益々汎用性が上がると思いますので、何卒検証頂きたくお願い致します。

**Comment by jtaka1012** [comment]
返信がおそくなりました。
ご連絡ありがとうございます。

こちらの事象ですが、TableView (ScrollViewを継承したView全般)にかかわる事象ではないでしょうか？
http://jtaka1012.hatenablog.com/entry/2015/03/06/070427

こちらの対応で解決することは出来ないでしょうか？
ご確認いただけますと幸いです。

**Comment by MasaruKitajima** [comment]
お世話になっております。

　ご指導有難うございます！お陰様で解決できました！

　貴作のSGLAccordionTableViewは非常に便利で重宝しています。本当に素晴らしい
物を有難うございます！

　改めて感謝申し上げます。

> 2016/08/21 10:44、jtaka1012 notifications@github.com のメール：
> 
> 返信がおそくなりました。
> ご連絡ありがとうございます。
> 
> こちらの事象ですが、TableView (ScrollViewを継承したView全般)にかかわる事象ではないでしょうか？
> http://jtaka1012.hatenablog.com/entry/2015/03/06/070427
> 
> こちらの対応で解決することは出来ないでしょうか？
> ご確認いただけますと幸いです。
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

<><><><><><><><><><><><><><><><><><><><><><><><><><>
Manager / PHP, JavaScript and iOS programmer
Masaru Kitajima

Prime Kobo LLC
a Delaware Limited Liability Company
https://www.prime-kobo.com

E-mail:kitajima@prime-kobo.com

+81-11-616-9437 (office)
+81-80-3293-2009
+81-80-5583-9839
<><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by jtaka1012** [comment]
いえいえ、解決されたようで良かったです！
本件クローズとさせていただきます。

ご連絡ありがとうございました。
